name: common_plugin
description: A new Flutter project.
version: 2.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  intl: ^0.19.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  camera: ^0.10.0
  cached_network_image: ^3.3.1
  wechat_assets_picker: ^9.3.1
  flutter_image_compress: ^2.3.0
  crop_your_image: ^1.1.0
  path_provider: ^2.1.3
  open_file: ^3.5.3
  syncfusion_flutter_datepicker: ^26.1.42
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: vip.caidou.common_plugin
        pluginClass: CommonPlugin
      ios:
        pluginClass: CommonPlugin

  assets:
    - assets/
    - assets/images/
#    - assets/emoji/
#    - assets/sound/
#    - assets/icon/


  fonts:
    - family: iconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf

